### ISSUE TITLE
Queue not restored on startup

### ISSUE THREAD

**Issue by mnightingale** [sabnzbd/sabnzbd#3269]
### SABnzbd version

develop

### Operating system

macos

### Using Docker image

None

### Description

Appears to have been broken by https://github.com/sabnzbd/sabnzbd/commit/17dcff49b25aaf3988bbc28f46175981908f9211

```
Traceback (most recent call last):
  File "/sabnzbd/sabnzbd/filesystem.py", line 1107, in load_data
    data = pickle.load(data_file, encoding=sabnzbd.encoding.CODEPAGE)
  File "/sabnzbd/sabnzbd/nzb/article.py", line 221, in __setstate__
    self.lock = self.nzf.nzo.lock
                ^^^^^^^^^^^^
AttributeError: 'sabnzbd.nzb.file.NzbFile' object has no attribute 'nzo'
```

**Comment by mnightingale** [comment]
I think object needs:

```
for nzf in self.files:
    for article in nzf.articles:
        article.lock = self.lock
```

But article also initially needs `self.lock = threading.RLock()` because file \_\_setstate\_\_ can call `add_to_try_list`

Or do it at nzf level and copy that lock, what was the reason to use nzo?

**Comment by Safihre** [comment]
It felt safer. But I can't come up with a clear reason why.. Probably nzf-level is also good?

**Comment by mnightingale** [comment]
Article currently calls synchronized on reset_try_list and allow_new_fetcher which operate on the article level trylist or nzf and nzo, so I think I'd just use nzf.

I don't think it actually makes any difference from a contention perspective, but it does make it simpler to reconstruct from the file level and shouldn't need the temporary locks.

It will need reordering of \_\_setstate\_\_ - actually that's a seperate bug, start a download then restart part way through for that.

`super().__setstate__(dict_.get("try_list", []))` need self.lock`
