### ISSUE TITLE
RSS feed: Incompatible RSS feed

### ISSUE THREAD

**Issue by DerzeitloseWolf** [sabnzbd/sabnzbd#1589]
Hi again,

unfournately I have another issue with version 3.0.1 (3.0.1 [9a4be70])

RSS feed, which is working fine with version 2.3.7 is not working with version 3 anymore. I have attched sabnzbd.log, there are some errors in it like

2020-08-27 21:51:33,421::INFO::[rss:345] Traceback: 
Traceback (most recent call last):
  File "feedparser.py", line 398, in __getattr__
  File "feedparser.py", line 356, in __getitem__
KeyError: 'cattext'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sabnzbd\rss.py", line 787, in _get_link
  File "feedparser.py", line 400, in __getattr__
AttributeError: object has no attribute 'cattext'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "feedparser.py", line 314, in __getitem__
IndexError: list index out of range
[sabnzbd.log](https://github.com/sabnzbd/sabnzbd/files/5138598/sabnzbd.log)

**Comment by Safihre** [comment]
If you add this feed's URL as a new feed, does it work? Just to check if maybe it was a problem with a conversion from 2.x or if it's a problem in general.
Is it a feed from a widely known indexer/engine?

**Comment by thezoggy** [comment]
Did you clear out the bytecode (pyc) files after upgrading?

**Comment by DerzeitloseWolf** [comment]
@Safihre I have tried both, modifying an existing feed and creating a new one, both are not working. Not sure, how known it is, it is a feed from WTFNZB
@thezoggy No, I didn't, what do I need to do?

**Comment by Safihre** [comment]
@DerzeitloseWolf could you send me the url via email at safihre@sabnzbd.org so I can try it?

**Comment by DerzeitloseWolf** [comment]
@Safihre Done :)

**Comment by DerzeitloseWolf** [comment]
Thx for your quick help. I have tested the new version and can confirm, it is working :)

**Comment by Safihre** [comment]
Strange this worked before, wonder what changed. Luckily the fix was easy 👍
