### ISSUE TITLE
Not working with >=feedparser-6.0.0b1: AttributeError: module 'feedparser' has no attribute '_FeedParserMixin'

### ISSUE THREAD

**Issue by Whissi** [sabnzbd/sabnzbd#1567]
In Gentoo we already have feedparser-6.0.0b1. However, with this version, sabnzbd-3.0.0 doesn't start:
```
$ /usr/share/sabnzbd/SABnzbd.py
2020-08-04 15:38:14,062::INFO::[SABnzbd:1136] --------------------------------
2020-08-04 15:38:14,062::INFO::[SABnzbd:1137] SABnzbd.py-3.0.0 (rev=cc465c75543dfa26e3065c7dbf98354d53ad1112)
2020-08-04 15:38:14,062::INFO::[SABnzbd:1138] Full executable path = /usr/share/sabnzbd/SABnzbd.py
2020-08-04 15:38:14,062::INFO::[SABnzbd:1148] Platform = posix
2020-08-04 15:38:14,062::INFO::[SABnzbd:1149] Python-version = 3.8.5 (default, Jul 24 2020, 02:46:56)
[GCC 10.2.0]
2020-08-04 15:38:14,062::INFO::[SABnzbd:1150] Arguments = "/usr/share/sabnzbd/SABnzbd.py"
2020-08-04 15:38:14,063::INFO::[SABnzbd:1154] Not inside a docker container
2020-08-04 15:38:14,063::INFO::[SABnzbd:1157] Preferred encoding = UTF-8
2020-08-04 15:38:14,063::INFO::[SABnzbd:1169] SSL version = OpenSSL 1.1.1g  21 Apr 2020
2020-08-04 15:38:14,063::INFO::[SABnzbd:1217] Using INI file /var/lib/sabnzbd/.sabnzbd/sabnzbd.ini
2020-08-04 15:38:14,063::INFO::[filesystem:305] download_dir directory: /var/lib/sabnzbd/Downloads/incomplete does not e
xist, try to create it
2020-08-04 15:38:14,063::INFO::[filesystem:564] Creating directories: /var/lib/sabnzbd/Downloads/incomplete (mask=448)
2020-08-04 15:38:14,065::INFO::[config:857] Writing settings to INI file /var/lib/sabnzbd/.sabnzbd/sabnzbd.ini
2020-08-04 15:38:14,067::INFO::[__init__:955] [N/A] /var/lib/sabnzbd/.sabnzbd/admin/rss_data.sab missing
Traceback (most recent call last):
  File "/usr/share/sabnzbd/SABnzbd.py", line 1721, in <module>
    main()
  File "/usr/share/sabnzbd/SABnzbd.py", line 1222, in main
    sabnzbd.initialize(pause, clean_up, evalSched=True, repair=repair)
  File "/usr/share/sabnzbd/sabnzbd/decorators.py", line 36, in call_func
    return f(*args, **kw)
  File "/usr/share/sabnzbd/sabnzbd/__init__.py", line 323, in initialize
    rss.init()
  File "/usr/share/sabnzbd/sabnzbd/rss.py", line 48, in init
    __RSS = RSSQueue()
  File "/usr/share/sabnzbd/sabnzbd/rss.py", line 209, in __init__
    patch_feedparser()
  File "/usr/share/sabnzbd/sabnzbd/rss.py", line 648, in patch_feedparser
    feedparser._FeedParserMixin.namespaces["http://www.newznab.com/DTD/2010/feeds/attributes/"] = "newznab"
AttributeError: module 'feedparser' has no attribute '_FeedParserMixin'
```
Downgrading to feedparser-5.2.1 make it work again.

**Comment by sanderjo** [comment]
Comes from https://github.com/sabnzbd/sabnzbd/blob/c4aad2a4bd03c215e05eab27d1835cb6c4291147/sabnzbd/rss.py#L640-L669 , which is a patch, for ... newznab ... is that still supported? That URL http://www.newznab.com/DTD/2010/feeds/attributes/ gives a 404 ... 

So ... remove all that?

@Safihre must know more

**Comment by Safihre** [comment]
It is very much supported by every indexer out there!
We know it doesn't work with 6.0.0, so that's why it's listed specifically:
https://github.com/sabnzbd/sabnzbd/blob/develop/requirements.txt#L4

So closing this, as it's something we are working on. We have time, since it's still in beta and almost no development seems to happen at all on it..

**Comment by Whissi** [comment]
Could you please keep this open until it is fixed? When I filed the issue I knew it will take some time... it's OK. But keep in mind that every package maintainer already looking into Python 3.9 will probably hit this soon. So an open bug will help them to recognize that you are already aware...

**Comment by Safihre** [comment]
Oke.
Strange you mention Python 3.9 compatibility, as feedparser 6. 0.0 doesn't work with the last Python 3.9 version.
https://github.com/kurtmckee/feedparser/pull/206
That exact pull request has gotten me very frustrated with the feedparser project.. It's been there for 5 months.

**Comment by Whissi** [comment]
There's a pending PR, https://github.com/kurtmckee/feedparser/pull/206

**Comment by Whissi** [comment]
Just a comment to keep stale bot away.

**Comment by Safihre** [comment]
@Whissi The PR kurtmckee/feedparser#206 is still open, going for 6 months now, and the repo is dead-silent..

**Comment by thezoggy** [comment]
repo was just updated.
